name: properCI

on:
  push:

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checout repo
        uses: actions/checkout@v4

      - name: set up jsnode
        uses: actions/setup-node@v4

      - run: npm ci

      - run: npm test && npm type check
      - run: npm 

  lint: 
    name: Run lint
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: npm run eslint
